first = input("What is your favorite animal?\n -->")
second = input("Why do you like this animal?\n -->")
third = input("Where does this animal live??\n -->")
fourth = input("What color is this animal??\n -->")
fifth = input("What biome does this animal live in?(Ex. ocean, forest, plains)\n -->")
sixth = input("What is the scientific name of this animal??\n -->")
seventh = input("Is this animal a Herbivore, Carnivore, or Omnivore??\n -->")
eighth = input("What does this animal eat??\n -->")
ninth = input("Is this animal a predator or is it prey??\n -->")
tenth = input("What is your least favorite animal??\n -->")


print("Your favorite animal is the " + first)
print("Your like this animal because " + second)
print("This animal lives in " + third)
print("The color of this animal is " + fourth)
print("This animal lives in the" + fifth)
print("The scientific name of this animal is " + sixth)
print("This animal is a/an " + seventh)
print("This animal eats " + eighth)
print("This animal is a " + ninth)
print("Your least favorite animal is the " + tenth)